### ISSUE TITLE
Mermoryerror raised when inferencing GW150914.

### ISSUE THREAD

**Issue by kevinkvothe** [gwastro/pycbc#1828]
I've installed the v1.7.5 pycbc-el7 container from docker hub. I've tried to inference with the same instructions from https://ligo-cbc.github.io/pycbc/latest/html/inference.html with the GW150914 files and it runs just fine with 4000,6000,7000 iterations, but as the results plotting the posteriors are not very accurate, I tried with 12000 iterations, just as the documentation says, and I always get this error:

Traceback (most recent call last):
  File "/home/pycbc/pycbc-software/bin/pycbc_inference", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===3cc8cc', 'pycbc_inference')
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-3cc8cc-py2.7.egg/EGG-INFO/scripts/pycbc_inference", line 296, in <module>
    max_iterations=opts.niterations + n_burnin)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-3cc8cc-py2.7.egg/pycbc/inference/sampler_base.py", line 587, in write_results
    max_iterations=max_iterations)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-3cc8cc-py2.7.egg/pycbc/inference/sampler_base.py", line 458, in write_chain
    samples = self.samples
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-3cc8cc-py2.7.egg/pycbc/inference/sampler_base.py", line 317, in samples
    names=sampling_args)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-3cc8cc-py2.7.egg/pycbc/io/record.py", line 1010, in from_arrays
    obj = numpy.rec.fromarrays(arrays, **kwargs).view(type=cls)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/numpy/core/records.py", line 621, in fromarrays
    _array = recarray(shape, descr)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/numpy/core/records.py", line 419, in __new__
    self = ndarray.__new__(subtype, shape, (record, descr), order=order)
MemoryError

when the loop goes from 7000 to 8000 interations. I've tried lowering the N_CHECKPOINT with values 500, 250 (and varying N_UPDATE with half these values) and still got the same error when the loop gets to 8000.

Any help would be appreciated, thanks.

**Comment by cdcapano** [comment]
@kevinkvothe I haven't run into this myself. Where are you running? How much memory do you have? How much memory is being used just prior to it failing? It shouldn't be increasing in memory by much after the first checkpoint, since it clears the chain in memory after it dumps the results to file.

**Comment by kevinkvothe** [comment]
I run it on windows 10 with an i7 and 8 Gb RAM, 6 of which can be used by Docker. I'll try monitoring the RAM to see how much is being used before the error raises. I thaught that too, other thing to notice is that the calculation takes longer after some checkpoints, like from 4 hours in the 0-1000 loop to 5 in the 5000-6000 iteration loop.

**Comment by GarethCabournDavies** [comment]
Can this be closed?

**Comment by cdcapano** [comment]
Yes, this can be closed.
