### ISSUE TITLE
pycbc_single_template_plot fails on headless systems due to import in legacy_grb

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2150]
Recent releases (testing on 1.9.4) break `pycbc_single_template_plot` on headless cluster nodes:
```
$ pycbc_single_template_plot --single-template-file H1.hdf --output-file ~/public_html/test.png --event-time 1186741861.53
/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/bin/pycbc_single_template_plot", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==1.9.4', 'pycbc_single_template_plot')
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/deploy/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/PyCBC-1.9.4-py2.7.egg/EGG-INFO/scripts/pycbc_single_template_plot", line 18, in <module>
    import argparse, pycbc.results, pycbc.events, pycbc.events, sys, h5py, numpy
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/PyCBC-1.9.4-py2.7.egg/pycbc/results/__init__.py", line 6, in <module>
    from pycbc.results.legacy_grb import *
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/PyCBC-1.9.4-py2.7.egg/pycbc/results/legacy_grb.py", line 37, in <module>
    import matplotlib.pyplot as plt
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.9.4/lib/python2.7/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named Tkinter
```
This seems due to an unfortunate series of imports. Rearranging them fixes the error. I will post an actual fix after some sleep.

**Comment by titodalcanton** [comment]
This error actually happens for *all* executables importing `pycbc.results` and probably needs a more general fix in `legacy_grb`'s matplotlib import (https://github.com/gwastro/pycbc/blob/master/pycbc/results/legacy_grb.py#L37). @spxiwh could you comment on this? Can I drop that import or move it into the function where it is used?

**Comment by a-r-williamson** [comment]
@titodalcanton `legacy_grb.make_grb_segments_plot` is only called from `pycbc_make_offline_grb_workflow` so could we not just set the backend there and remove it from `legacy_grb.py`?

**Comment by a-r-williamson** [comment]
@titodalcanton no strong peference. I can review if you make a PR, otherwise I'll do it and get @pannarale to review. Thanks.

**Comment by spxiwh** [comment]
This looks like it should be a function-level import of *just* matplotlib.pyplot. The `'agg'` stuff should be done at the level of any executable that needs it.

**Comment by titodalcanton** [comment]
This issue is now resolved.
