### ISSUE TITLE
The workflow test needs to be fixed

### ISSUE THREAD

**Issue by duncan-brown** [gwastro/pycbc#2289]
https://github.com/gwastro/pycbc/pull/2280 has introduced a two bugs in the workflow test. The first is that a failing workflow test isn't actually causing the test to fail (which may have predated this bug), and the second is that the segment name `H1:DCS-ANALYSIS_READY_C02` needs to be overridden to use 

```
[workflow]
; http://ligo-cbc.github.io/pycbc/releases/v1.2.0/html/workflow/initialization.html
h1-channel-name = H1:GWOSC-16KHZ_R1_STRAIN
l1-channel-name = L1:GWOSC-16KHZ_R1_STRAIN

[workflow-datafind]
; http://ligo-cbc.github.io/pycbc/releases/v1.2.0/html/workflow/datafind.html
datafind-h1-frame-type = H1_LOSC_16_V1
datafind-l1-frame-type = L1_LOSC_16_V1

[workflow-segments]
segments-h1-science-name = H1:RESULT:1
segments-l1-science-name = L1:RESULT:1
segments-database-url = https://losc.ligo.org/archive/O1/ 
```

Error message is below:

```
2018-08-16 13:34:02,179:INFO : Starting generation of science segments
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/bin/pycbc_make_coinc_search_workflow", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===27ce96', 'pycbc_make_coinc_search_workflow')
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    exec(code, namespace, namespace)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/lib/python2.7/site-packages/PyCBC-27ce96-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_make_coinc_search_workflow", line 126, in <module>
    rdir['analysis_time/segment_data'])
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/lib/python2.7/site-packages/PyCBC-27ce96-py2.7-linux-x86_64.egg/pycbc/workflow/segment.py", line 79, in get_science_segments
    workflow.cp, start_time, end_time, out_dir, tags)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-master/lib/python2.7/site-packages/PyCBC-27ce96-py2.7-linux-x86_64.egg/pycbc/workflow/segment.py", line 698, in get_sci_segs_for_ifo
    sci_xml_file.seg_summ_dict[':'.join(sci_seg_name.split(':')[0:2])]
KeyError: 'H1:DCS-ANALYSIS_READY_C02'
/pycbc/workflow-test/test-workflow-319e140c-bb45-4c52-9476-0ee6a048e65a/output /pycbc/workflow-test/test-workflow-319e140c-bb45-4c52-9476-0ee6a048e65a /pycbc/workflow-test
>> [Thu Aug 16 13:34:04 UTC 2018] Validating workflow *.dax
java.io.FileNotFoundException: /pycbc/workflow-test/test-workflow-319e140c-bb45-4c52-9476-0ee6a048e65a/output/*.dax (No such file or directory)
>> [Thu Aug 16 13:34:05 UTC 2018] Planning test workflow
ERROR: Couldn't find a valid proxy.
       globus_sysconfig: Could not find a valid proxy certificate file location
globus_sysconfig: Error with key filename
globus_sysconfig: File does not exist: /tmp/x509up_u0 is not a valid file
Use -debug for further information.
Error: Could not find a valid grid proxy to submit workflow.
/pycbc/workflow-test/test-workflow-319e140c-bb45-4c52-9476-0ee6a048e65a /pycbc/workflow-test
/pycbc/workflow-test
```

**Comment by duncan-brown** [comment]
@vahi I can't figure out how to stop `pegasus-plan` testing for a grid proxy. I tried adding `--forward nogrid` and `--nogrid` to the command line, but in both cases it fails with
```
ERROR: Couldn't find a valid proxy.
       globus_sysconfig: Could not find a valid proxy certificate file location
globus_sysconfig: Error with key filename
globus_sysconfig: File does not exist: /tmp/x509up_u0 is not a valid file
Use -debug for further information.
Error: Could not find a valid grid proxy to submit workflow.
```

Any idea how to disable this check?

**Comment by duncan-brown** [comment]
Leaving this open as https://github.com/gwastro/pycbc/pull/2290 has disabled pegasus-plan until I can figure out the nogrid option.
