### ISSUE TITLE
memory leak in pycbc live

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#2430]
There is a memory leak in pycbc live which needs to be tracked down. More details to follow.

**Comment by titodalcanton** [comment]
Here are some details after reviewing the supervisord log and the recent stderr logs. The analysis went through several days of instability, after which it has been running stably for the last two weeks. So this might be a data-quality-dependent issue. Currently I see an RSS of 20.4 Gb on the master process and 10 Gb on one of the worker nodes. The error message from the last failure I have on record is as follows:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3exp/env/bin/pycbc_live", line 528, in <module>
    coinc_results = estimator.add_singles(results, data_reader)
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 927, in add_singles
    updated_indices = self._add_singles_to_buffer(results)
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 749, in _add_singles_to_buffer
    self.singles[ifo].add(trigs['template_id'], data)
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 425, in add
    self.increase_buffer_size(int(self.pad_count * 1.5 + 5))
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 382, in increase_buffer_size
    self.buffer = numpy.resize(self.buffer, (self.num_rings, size))
  File "/home/pycbc.live/production/O3exp/env/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1229, in resize
    a = concatenate((a,) * n_copies)
MemoryError
```

**Comment by spxiwh** [comment]
Is this actually a memory leak, and not just "There were gazillions of triggers at one", possibly because the data was garbage.

**Comment by titodalcanton** [comment]
New data point: the analysis has been up for ~3 days, the current RSS of the master process is 128 Gb and 12 Gb on one of the worker processes.

**Comment by titodalcanton** [comment]
This was greatly improved by #2523. I do not see significant increase of memory usage over a few days. I will close this once it remains stable for a few weeks.

**Comment by titodalcanton** [comment]
I do not think I see any more trace of memory leaks, so I am closing this for now.
