### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lhm315** [gwastro/pycbc#2448]
Run GW150914 example, there will be some errors:
Traceback (most recent call last):
  File "/home/luo/opt/anaconda2/bin/pycbc_inference", line 174, in <module>
    injection_file=injection_file)
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/inference/sampler/base.py", line 173, in setup_output
    backup_file)
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/inference/io/__init__.py", line 202, in validate_checkpoint_files
    check_integrity(checkpoint_file)
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/inference/io/__init__.py", line 156, in check_integrity
    ref_shape = fp[group.format(parameters[0])].shape
IndexError: list index out of range
What is the cause of this error? Thank you very much.

**Comment by GarethCabournDavies** [comment]
Stale, will close
