### ISSUE TITLE
problems with determine CPU caches with getconf on virtual machine 

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#2460]
We've had a report that pycbc fails to install with this message
```
root@Hilbert:~# pip install pycbc
Collecting pycbc
  Using cached https://files.pythonhosted.org/packages/78/e0/49a160871ecef3f426d2709b8a673155883b749cd622164225359219cc51/PyCBC-1.13.2.tar.gz …
    Complete output from command python http://setup.py  egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VEVfaF/pycbc/setup.py", line 203, in <module>
        VERSION = get_version_info()
      File "/tmp/pip-build-VEVfaF/pycbc/setup.py", line 114, in get_version_info
        from pycbc import _version_helper
      File "pycbc/__init__.py", line 146, in <module>
        import pycbc.fft.mkl
      File "pycbc/fft/__init__.py", line 17, in <module>
        from .parser_support import insert_fft_option_group, verify_fft_options, from_cli
   File "pycbc/fft/parser_support.py", line 29, in <module>
        from .backend_support import get_backend_modules, get_backend_names
      File "pycbc/fft/backend_support.py", line 77, in <module>
        mod = __import__('pycbc.fft.backend_' + scheme_name, fromlist = ['_alist', '_adict'])
      File "pycbc/fft/backend_cpu.py", line 18, in <module>
        from .core import _list_available
      File "pycbc/fft/core.py", line 29, in <module>
        from pycbc.types import Array as _Array
      File "pycbc/types/__init__.py", line 1, in <module>
        from .array import *
      File "pycbc/types/array.py", line 45, in <module>
        from pycbc.opt import LimitedSizeDict
      File "pycbc/opt.py", line 124, in <module>
        LEVEL3_CACHE_SIZE = getconf('LEVEL3_CACHE_SIZE')
      File "pycbc/opt.py", line 112, in getconf
        return int(subprocess.check_output(['getconf', confvar]))
    ValueError: invalid literal for int() with base 10: 'undefined\n'
```
Looking into it they are running in a virtual machine with an emulated CPU. I think the problem here is that we assume that the output of getconf is *always* a number. However, there is no actual guarantee that a flag will report as such and it *is* valid for it to return "undefined" which is doing and failing when we try to convert to an integer.

**Comment by ahnitz** [comment]
@josh-willis Should the getconf python function check for non-int output and have a fallback if an undefined or similar is returned?
