### ISSUE TITLE
Pegasus issue in workflow generation 

### ISSUE THREAD

**Issue by idorrington92** [gwastro/pycbc#2493]
When trying to run the pygrb workflow generation script I get the following error:
Traceback (most recent call last):
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/bin/pycbc_make_offline_grb_workflow", line 80, in <module>
    sciSegs, segsFileList = _workflow.setup_segment_generation(wflow, segDir)
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/lib/python2.7/site-packages/pycbc/workflow/segment.py", line 449, in setup_segment_generation
    analSegs.remove_short_sci_segs(minSegLength)
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/lib/python2.7/site-packages/pycbc/workflow/core.py", line 1786, in remove_short_sci_segs
    self.to_segment_xml(override_file_if_exists=True)
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/lib/python2.7/site-packages/pycbc/workflow/core.py", line 1839, in to_segment_xml
    site='local')
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/lib/python2.7/site-packages/Pegasus/DAX3.py", line 504, in PFN
    self.addPFN(PFN(url, site))
  File "/home/c1551011/PyGRB_O3_dev/src/pygrbo3dev/lib/python2.7/site-packages/Pegasus/DAX3.py", line 485, in addPFN
    raise DuplicateError("Duplicate PFN %s" % pfn)
Pegasus.DAX3.DuplicateError: Duplicate PFN <PFN local file:///home/c1551011/coherent_pycbc/integrated_analysis_all_segs_all_templates/GRB161217128/segments/H1-SCIENCE_OK_SEGMENTS.xml>

 Figured out a fix and will include it in this pull request https://github.com/gwastro/pycbc/pull/2476

**Comment by spxiwh** [comment]
@duncan-brown Did you identify how this problem actually managed to happen? The proposed fix makes sense (it simplifies the code), but I'm not sure what inputs caused this problem to happen in the first place??

**Comment by duncan-brown** [comment]
No idea. Something must have pushed the same PFN into the DAX twice, but if the PFN handling is done in the standard way, it should not happen. The changes in https://github.com/gwastro/pycbc/pull/2476/files#diff-861f78f8aa48c0d7ff28c6d745e2b974 clean up the code, but don't change the logic so I don't see how this could fix it. Were there other changes that could fix it?

**Comment by spxiwh** [comment]
Think I got into a @duncan-brown @duncanmmacleod confusion here. I'll just tag everyone :). But yeah, clearly the changed code is nicer, but I don't think it actually changed anything. Oh well, unless this happens again we can ignore.

**Comment by duncanmmacleod** [comment]
@duncan-brown, the logic _is_ changed. Before the patch the arguments to `self.has_pfn` and `self.PFN` (on either side of the if statement) **are different**, in the updated patch they both point at the new `url` variable, so are by design the same. This was the bug, other changes are purely cosmetic.
