### ISSUE TITLE
Pegasus issue in pygrb workflow generation

### ISSUE THREAD

**Issue by idorrington92** [gwastro/pycbc#2494]
The pygrb workflow generation gets as far as trying to submit the dax, when I get the following pagasus error:

2019.02.07 11:16:41.159 GMT: [FATAL ERROR]  
 [1]:  Unable to instantiate Transformation Catalog  at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:172)
 [2]: edu.isi.pegasus.planner.catalog.transformation.impl.Text caught edu.isi.pegasus.planner.parser.ScannerException line 3: unknown character 6 at edu.isi.pegasus.planner.parser.TransformationCatalogTextScanner.nextToken(TransformationCatalogTextScanner.java:222) 
ERROR while logging metrics The metrics file location is not yet initialized

**Comment by spxiwh** [comment]
@idorrington92 Please report the identified problem and solution here.

**Comment by idorrington92** [comment]
Due to a change in how DAGs work, the use of double quotes " in one of the ini files caused the set up to break. To fix this, we changed the ini file to use the escape character first, so \" instead of ".
