### ISSUE TITLE
Example pycbc inference not working

### ISSUE THREAD

**Issue by SwethaPBhagwat** [gwastro/pycbc#2502]
I am trying to follow the first example in Simulated BBH example from the documentation page. I get the following error. The error seems to get fixed when I remove the lower frequency option from the ini file. 

```Traceback (most recent call last):
 20   File "/home/swetha.bhagwat/Projects/Development_PYCBC_after_the_major_PE_change/bin/pycbc_inference", l    ine 152, in <module>
 21     model = models.read_from_config(cp, **model_args)
 22   File "/home/swetha.bhagwat/Projects/Development_PYCBC_after_the_major_PE_change/lib/python2.7/site-pack    ages/pycbc/inference/models/__init__.py", line 171, in read_from_config
 23     return models[name].from_config(cp, **kwargs)
 24   File "/home/swetha.bhagwat/Projects/Development_PYCBC_after_the_major_PE_change/lib/python2.7/site-pack    ages/pycbc/inference/models/base_data.py", line 238, in from_config
 25     return cls(**args)
 26   File "/home/swetha.bhagwat/Projects/Development_PYCBC_after_the_major_PE_change/lib/python2.7/site-pack    ages/pycbc/inference/models/gaussian_noise.py", line 222, in __init__
 27     waveform_generator, **kwargs)
 28   File "/home/swetha.bhagwat/Projects/Development_PYCBC_after_the_major_PE_change/lib/python2.7/site-pack    ages/pycbc/inference/models/base_data.py", line 91, in __init__
 29     variable_params, **kwargs)
 30 TypeError: __init__() got an unexpected keyword argument 'low-frequency-cutoff'```

**Comment by Cyberface** [comment]
Hi @SwethaPBhagwat, I believe this was changed in this MR https://github.com/gwastro/pycbc/pull/2456

Are you perhaps using an outdated version of pycbc?

@cdcapano will know for sure though.

**Comment by cdcapano** [comment]
@SwethaPBhagwat Yeah, you need to use the master version of pycbc, not the current release. Note that the documentation page is for current master, not the current release.

**Comment by stevereyes01** [comment]
Thanks for clearing that up for us Collin.
