### ISSUE TITLE
PyCBC Live error when recording an event

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2547]
Error from today's master:
```
2019-03-04 15:24:09,514 node742 Generating SPAtmplt, 88.0s, 184675, starting from 25.0 Hz
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/bin/pycbc_live", line 602, in <module>
    data_reader, bank)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/bin/pycbc_live", line 173, in check_coincs
    bank, followup_ifos)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/bin/pycbc_live", line 125, in compute_followup_data
    check_state=False)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/filter/matchedfilter.py", line 1879, in compute_followup_snr_series
    return snr[onsource_slice] * norm
  File "</home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/decorator.pyc:decorator-gen-120>", line 2, in __getitem__
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/array.py", line 67, in _convert
    return fn(self, *args)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/array.py", line 799, in __getitem__
    return self._getslice(index)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/timeseries.py", line 114, in _getslice
    return TimeSeries(Array._getslice(self, index), new_delta_t,
  File "</home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/decorator.pyc:decorator-gen-119>", line 2, in _getslice
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/array.py", line 223, in _memoize_single
    res = fn(self, arg) # pylint:disable=not-callable
  File "</home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/decorator.pyc:decorator-gen-118>", line 2, in _getslice
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/array.py", line 233, in _returntype
    ary = fn(self,*args) # pylint:disable=not-callable
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/array.py", line 791, in _getslice
    return self._return(self._data[index])
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/timeseries.py", line 88, in _return
    return TimeSeries(ary, self._delta_t, epoch=self._epoch, copy=False)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/types/timeseries.py", line 58, in __init__
    raise ValueError('initial_array must contain at least one sample.')
ValueError: initial_array must contain at least one sample.
```

**Comment by ahnitz** [comment]
Huh, I don't see anything on first glance. @titodalcanton Do you think it's possible to reproduce this one? What we'd want to see is what trig_time and valid_start / valid_end are set to.

**Comment by titodalcanton** [comment]
I will add an assert and have it print those values. Looks like it is not happening with every coinc, but quite frequently nevertheless.

**Comment by titodalcanton** [comment]
So apparently this happened twice during a brief period of crazy glitchy data. I have not seen it after that. Let's keep this error in mind and hopefully I find some time to implement a proper unit test.

**Comment by titodalcanton** [comment]
Just caught another case, with a bit more verbose logging:
```
[…]
2019-03-08 08:23:34,503 node742 computing followup data for coinc
2019-03-08 08:23:34,504 node742 Generating SPAtmplt, 80.0s, 201376, starting from 25.1 Hz
2019-03-08 08:23:34,603 node742 BAYESTAR DEBUG: trig_time 1236097412.0297852 snr.start_time 1236097328.569335937 onsource_idx 170927 onsource_slice slice(170830, 171025, None) len(snr) 163840
Traceback (most recent call last):
[…]
```

**Comment by ahnitz** [comment]
@titodalcanton Has this one reoccurred?

**Comment by titodalcanton** [comment]
Yes, this keeps happening every once in a while. I can post the log with all the involved variables when it happens again.

**Comment by ahnitz** [comment]
@titodalcanton Did you find any reproducing case in offline data?

**Comment by titodalcanton** [comment]
Not so far, but I didn't do a full rerun on my fake frames after the various recent fixes were put in. I just started it.

**Comment by titodalcanton** [comment]
Looking again at my last log message above, the issue seems to be that the trigger time is somehow past the end of the full SNR time series right? The trigger time is ~83 s after the start of the time series, and the time series is 80 s long. Does this mean that somehow the worker and master nodes got out of sync on which data segment they are analyzing? I thought all the padding was being properly accounted for, at least to ~1 s…

**Comment by titodalcanton** [comment]
I completed the analysis of my offline fake frames and could not reproduce the error.

**Comment by ahnitz** [comment]
@titodalcanton Indeed. I'm a bit confused how this one could come about.

**Comment by ahnitz** [comment]
I don't think (if MPI is working correctly) that it's possible for the analysis to get out of sync in this way.

**Comment by ahnitz** [comment]
I say this since synchronization should be guaranteed by MPI as that would require that either the commit_results (for rank > 0) or the gather_results ( for master) can be bypassed. 

As long as the loop can't skip here. 
https://github.com/gwastro/pycbc/blob/master/bin/pycbc_live#L574

**Comment by ahnitz** [comment]
@titodalcanton For the other instances is the time off by the same amount? (i.e. ~3.5 s) Or is it a range?

**Comment by titodalcanton** [comment]
One more case:

`2019-03-12 16:33:27,258 node742 compute_followup_snr_series: trig_time 1236468781.8168945 snr.start_time 1236468720.569335937 snr.end_time 1236468776.569335937 onsource_idx 125435 onsource_slice slice(125338, 125533, None) len(snr) 114688`

So this triggers is 5 s after the SNR end time, while the previous case had it 3.5 s after SNR end time.

**Comment by ahnitz** [comment]
@titodalcanton Has this issue been observed again?

**Comment by titodalcanton** [comment]
No, not in the last ~4 days, either in the production or replay analysis. I am closing this for now.
