### ISSUE TITLE
PyCBC Live creates SNR time series with slightly different sample period

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2563]
At the end of `compute_followup_data()`, the SNR time series can have slightly different sample periods, for example 0.00048828125 and 0.0004882812500000001. This is a problem when the candidate is uploaded to GraceDB and BAYESTAR tries to localize it, as it requires all timings to be identical. We need to track where exactly the discrepancy is happening.

**Comment by titodalcanton** [comment]
I restarted the replay analysis with the #2580 commit. Let's see how it does.

**Comment by titodalcanton** [comment]
The problem seems to happen still:
```
2019-03-25 06:06:53,015 node742 Found V1-L1 coinc with ifar 0.000260254144117
2019-03-25 06:06:53,015 node742 computing followup data for coinc
2019-03-25 06:06:53,016 node742 Generating SPAtmplt, 96.0s, 299411, starting from 25.0 Hz
2019-03-25 06:06:53,213 node742 Generating SPAtmplt, 288.0s, 299411, starting from 25.0 Hz
2019-03-25 06:06:55,501 node742 Adding H1 to candidate, pvalue 0.9426585577758471, 6905 samples
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/bin/pycbc_live", line 631, in <module>
    data_reader, bank)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/bin/pycbc_live", line 184, in check_coincs
    assert len({fud[ifo]['snr_series'].delta_t for ifo in live_ifos}) == 1
AssertionError
```

**Comment by titodalcanton** [comment]
A bruteforce solution is in #2592 and it works, so I am closing this.
