### ISSUE TITLE
TypeError in PyCBC Live followup

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2604]
A new issue from the replay analysis using master at aeb0ac4d6498b81f8d95f78bf41fddbb7cf751d6:
```
2019-03-29 05:35:08,521 node742 Found V1-H1 coinc with ifar 0.000183082374766
2019-03-29 05:35:08,522 node742 computing followup data for coinc
2019-03-29 05:35:08,523 node742 Generating SPAtmplt, 72.0s, 140028, starting from 25.0 Hz
2019-03-29 05:35:08,688 node742 Generating SPAtmplt, 272.0s, 140028, starting from 25.0 Hz
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/bin/pycbc_live", line 635, in <module>
    data_reader, bank)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/bin/pycbc_live", line 181, in check_coincs
    data_readers, bank, followup_ifos)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/bin/pycbc_live", line 134, in compute_followup_data
    data_readers[ifo], bank, template_id, coinc_times)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/pycbc/filter/matchedfilter.py", line 1781, in followup_event_significance
    stilde = data_reader.overwhitened_data(htilde.delta_f)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/pycbc/strain/strain.py", line 1446, in overwhitened_data
    psdt = pycbc.psd.interpolate(self.psd, fseries.delta_f)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env/lib/python2.7/site-packages/pycbc/psd/estimate.py", line 276, in interpolate
    new_n = (len(series)-1) * series.delta_f / delta_f + 1
TypeError: object of type 'NoneType' has no len()
```

**Comment by titodalcanton** [comment]
Like #2587, this happened during a moment of high lag.

**Comment by titodalcanton** [comment]
This has not been showing up in more than two weeks of continuous run of two analyses, so I am closing for now.
