### ISSUE TITLE
IndexError in PyCBC Live followup

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2622]
This one showed up in the production analysis, also at a moment of maximum lag.
```
2019-04-03 08:56:42,398 node742 39088 background and zerolag coincs
2019-04-03 08:56:42,405 node742 clustering coinc triggers over 8s window
2019-04-03 08:56:42,406 node742 Clustering events over 8 s window
2019-04-03 08:56:42,459 node742 16320 triggers remaining
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/bin/pycbc_live", line 630, in <module>
    coinc_results.append(c.add_singles(results, data_reader))
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 1125, in add_singles
    ifos=valid_ifos)
  File "/home/pycbc.live/production/O3/pycbc_live_O3_production_env/lib/python2.7/site-packages/pycbc/events/coinc.py", line 1056, in _find_coincs
    trig_id = trigger_ids[ifo][idx]
IndexError: list index out of range
```

**Comment by titodalcanton** [comment]
This has not been showing up in more than a week of continuous run of two analyses, so I am closing for now.
