### ISSUE TITLE
pycbc_make_inference_workflow : special character error from parsing prior sections

### ISSUE THREAD

**Issue by dbkeitel** [gwastro/pycbc#2740]
In 1.13.8 pycbc_make_inference_workflow fails when there are two-parameter combined prior sections (e.g. "[prior-spin1_polar+spin1_azimuthal]") in the inference ini file, with
`2019.05.30 09:15:48.023 PDT: [FATAL ERROR]  
 [1]:  Unable to instantiate Transformation Catalog  at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:172)
 [2]: edu.isi.pegasus.planner.catalog.transformation.impl.Text caught edu.isi.pegasus.planner.parser.ScannerException line 11: unknown character + at edu.isi.pegasus.planner.parser.TransformationCatalogTextScanner.nextToken(TransformationCatalogTextScanner.java:226)`
in the subdax_bbh_inference_test-main_ID0000001.pre.err.000 file in my test case.

As a temporary work-around @spxiwh suggested to simply comment out the call to make_inference_prior_plot() which isn't essential to the rest of the workflow, but he'll investigate proper "+" character sanitising later.

**Comment by cdcapano** [comment]
Fixed by #3140.
