### ISSUE TITLE
Runtime Error due to SimNoise() while generating Gaussian noise using pycbc.noise module

### ISSUE THREAD

**Issue by rutujagurav** [gwastro/pycbc#2822]
I am running this example code from pycbc documentation in order to generate gaussian noise.

```
import pycbc.noise
import pycbc.psd
import matplotlib.pyplot as plt

# The color of the noise matches a PSD which you provide
flow = 30.0
delta_f = 1.0 / 16
flen = int(2048 / delta_f) + 1
psd = pycbc.psd.aLIGOZeroDetHighPower(flen, delta_f, flow)

# Generate 32 seconds of noise at 4096 Hz
delta_t = 1.0 / 4096
tsamples = int(32 / delta_t)
ts = pycbc.noise.noise_from_psd(tsamples, delta_t, psd, seed=127)

plt.plot(ts.sample_times, ts)
plt.ylabel('Strain')
plt.xlabel('Time (s)')
plt.show()

```

I get the following error - 
_XLAL Error - XLALCreateREAL8FFTPlan (RealFFT_source.c:120): Generic failure
XLAL Error - XLALCreateReverseREAL8FFTPlan (RealFFT_source.c:145): Internal function call failed: Generic failure
XLAL Error - XLALSimNoiseSegment (LALSimNoise.c:50): Internal function call failed: Generic failure
Traceback (most recent call last):
  File "generating-noise.py", line 14, in <module>
    ts = pycbc.noise.noise_from_psd(tsamples, delta_t, psd, seed=127)
  File "/home/.../anaconda3/lib/python3.6/site-packages/pycbc/noise/gaussian.py", line 117, in noise_from_psd
    SimNoise(segment, 0, psd, randomness)
RuntimeError: Internal function call failed: Generic failure_

I am using pycbc version 1.14.0 in a python 3.6.8 environment.

**Comment by rutujagurav** [comment]
I think this is a python3 problem. Code runs fine in python 2.7 environment.

**Comment by ahnitz** [comment]
@rutujagurav Thanks for the report.

I quickly tested on my personal machine with python 3.7.3 (don't have 3.6 on hand) and python 2.7.16. It seems to work on both for me with PyCBC version 1.14.0. 

It's possible the python version is a red herring here, though I'm not completely sure. The error indicates a problem creating an FFT plan (using fftw internally) within lalsimulation. FFTW *should* be bundled with the lalsimulation package. I get the following linkage to lalsimulation in my install. 
```
	linux-vdso.so.1 (0x00007fff97b6e000)
	liblalsimulation-b085b2f1.so.20.0.0 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/liblalsimulation-b085b2f1.so.20.0.0 (0x00007f5f7e52e000)
	liblalsupport-2b8341a5.so.12.1.0 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/liblalsupport-2b8341a5.so.12.1.0 (0x00007f5f7e1a0000)
	libhdf5_hl-ed6740ef.so.100.1.2 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libhdf5_hl-ed6740ef.so.100.1.2 (0x00007f5f7df78000)
	libhdf5-85dbb784.so.103.1.0 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libhdf5-85dbb784.so.103.1.0 (0x00007f5f7d998000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f5f7d95d000)
	libz-a147dcb0.so.1.2.3 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libz-a147dcb0.so.1.2.3 (0x00007f5f7d746000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5f7d740000)
	liblal-f7f0c154.so.17.0.1 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/liblal-f7f0c154.so.17.0.1 (0x00007f5f7d3ac000)
	libfftw3-c8dcb815.so.3.2.4 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libfftw3-c8dcb815.so.3.2.4 (0x00007f5f7d0a4000)
	libfftw3f-044fdcc5.so.3.2.4 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libfftw3f-044fdcc5.so.3.2.4 (0x00007f5f7cda2000)
	libgsl-a173566c.so.23.1.0 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libgsl-a173566c.so.23.1.0 (0x00007f5f7c8f5000)
	libgslcblas-96f7e846.so.0.0.0 => /home/ahnitz/projects/env3/lib/python3.7/site-packages/lalsimulation/./../lalsuite.libs/libgslcblas-96f7e846.so.0.0.0 (0x00007f5f7c6b8000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5f7c572000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5f7c551000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5f7c38b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5f7f2fa000)
```

@rutujagurav What's your OS and what's the version of the lalsuite package you are using in both environment?

I am using the following 
```
(env3) [ahnitz@localhost lalsimulation]$ pip show lalsuite
Name: lalsuite
Version: 6.59
Summary: LIGO Scientific Collaboration Algorithm Library - minimal Python package
Home-page: https://git.ligo.org/lscsoft/lalsuite
Author: LIGO Scientific Collaboration
Author-email: lal-discuss@ligo.org
License: GPL-2+
Location: /home/ahnitz/projects/env3/lib/python3.7/site-packages
Requires: matplotlib, scipy, numpy, ligo-segments, python-dateutil, lscsoft-glue
Required-by: 
```

**Comment by rutujagurav** [comment]
Thanks for the swift reply. 
For python 2.7 environment, this is the lalsuite package.
```
rutuja@server $ pip show lalsuite
Name: lalsuite
Version: 6.53
Summary: None
Home-page: None
Author: None
Author-email: None
License: None
Location: /home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages
Requires:
Required-by: gwsumm

```

For python 3.6.8 environment, this is the lalsuite package.

```
rutuja@server $ pip show lalsuite
Name: lalsuite
Version: 6.59
Summary: LIGO Scientific Collaboration Algorithm Library - minimal Python package
Home-page: https://git.ligo.org/lscsoft/lalsuite
Author: LIGO Scientific Collaboration
Author-email: lal-discuss@ligo.org
License: GPL-2+
Location: /home/.../anaconda3/lib/python3.6/site-packages
Requires: numpy, python-dateutil, matplotlib, ligo-segments, scipy, lscsoft-glue
Required-by:
```

**Comment by ahnitz** [comment]
@rutujagurav So did you install through the conda packages? I didn't check that. Lalsuite might be packaged differently there. I'll give that a try.

**Comment by rutujagurav** [comment]
For the python3 environment, I followed the documentation and installed lalsuite and pycbc using pip.
For the python2 environment, I used conda to install them. 
Regardless of whether I use pip or conda to install lalsuite and pycbc, it all works fine in the python2 environment.

**Comment by rutujagurav** [comment]
I uninstalled and reinstalled lalsuite and pycbc using pip in both python2 and python3 environments and the bug persists in python3 environment.

lalsuite package in python 3.6.8 environment:

```
rutuja@server $ pip show lalsuite
Name: lalsuite
Version: 6.59
Summary: LIGO Scientific Collaboration Algorithm Library - minimal Python package
Home-page: https://git.ligo.org/lscsoft/lalsuite
Author: LIGO Scientific Collaboration
Author-email: lal-discuss@ligo.org
License: GPL-2+
Location: /home/.../anaconda3/lib/python3.6/site-packages
Requires: numpy, scipy, lscsoft-glue, python-dateutil, ligo-segments, matplotlib
Required-by:
```

lalsuite in python 2.7.15:

```
rutuja@server $ pip show lalsuite
Name: lalsuite
Version: 6.59
Summary: LIGO Scientific Collaboration Algorithm Library - minimal Python package
Home-page: https://git.ligo.org/lscsoft/lalsuite
Author: LIGO Scientific Collaboration
Author-email: lal-discuss@ligo.org
License: GPL-2+
Location: /home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages
Requires: matplotlib, ligo-segments, numpy, scipy, lscsoft-glue, python-dateutil
Required-by:

```
It has to be a python 3.6 issue. A hassle-free thing to do would be to just use Python 3.7+ for a python3 environment as python2 will be deprecated and will no longer be maintained after the end of this year.

**Comment by rutujagurav** [comment]
This problem still persists for Python 3.10.12. I am on a non LIGO machine, following is my python environment.

```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
astropy                   5.3.2                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blas                      1.0                         mkl  
bottleneck                1.3.5           py310ha9d4c09_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cryptography              41.0.3                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.0                    pypi_0    pypi
fonttools                 4.42.1                   pypi_0    pypi
gwdatafind                1.1.3                    pypi_0    pypi
h5py                      3.9.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
igwn-auth-utils           1.0.1                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
jinja2                    3.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lalsuite                  7.19                     pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
ligo-segments             1.4.0                    pypi_0    pypi
lscsoft-glue              3.0.1                    pypi_0    pypi
mako                      1.2.4                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46343  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.6           py310h1128e8f_1  
mkl_random                1.2.2           py310h1128e8f_1  
mpld3                     0.5.9                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numexpr                   2.8.4           py310h85018f9_1  
numpy                     1.25.2          py310h5f9d8c6_0  
numpy-base                1.25.2          py310hb5e798b_0  
openssl                   3.0.10               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3           py310h1128e8f_0  
pegasus-wms-api           5.0.6                    pypi_0    pypi
pegasus-wms-common        5.0.6                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1          py310h06a4308_0  
pycbc                     2.2.1                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.0.3                  pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
pykerr                    0.1.0                    pypi_0    pypi
pyopenssl                 23.2.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrxp                     3.0.1                    pypi_0    pypi
python                    3.10.12              h955ad1f_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-ligo-lw            1.8.3                    pypi_0    pypi
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2022.7          py310h06a4308_0  
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
safe-netrc                1.0.1                    pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
scitokens                 1.8.1                    pypi_0    pypi
setuptools                68.0.0          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.12               h1ccaba5_0  
tqdm                      4.66.1                   pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   2.0.4                    pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0
```

**Comment by gregbaltus** [comment]
I'm having the same issue. I managed to solve the problem by installing lalsuite via conda (my pycbc was also installed by conda) :

 conda install conda-forge::lalsuite=7.22
