### ISSUE TITLE
results module is broken due to table

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2876]
typical error output:
```
Traceback (most recent call last):
  File "/home/gdavies/environments/pycbc-dev/bin/pycbc_page_segtable", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===b338b9', 'pycbc_page_segtable')
  File "/home/gdavies/environments/pycbc-dev/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gdavies/environments/pycbc-dev/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/gdavies/environments/pycbc-dev/lib64/python2.7/site-packages/PyCBC-b338b9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_page_segtable", line 182, in <module>
    html_table = pycbc.results.table(vals, keys, page_size=10)
TypeError: 'module' object is not callable
```
Since results.table contains a function called 'table' we're not sure why the code worked in the first place.

**Comment by tdent** [comment]
appears to be fixed by #2877 - still somewhat mysterious as to why this just started causing errors since the namespace clash has been around for years.
