### ISSUE TITLE
Adding noise to a waveform

### ISSUE THREAD

**Issue by rutujagurav** [gwastro/pycbc#2903]
Forgive me if I am completely missing the point here, I am new to pycbc.
I am trying to generate a population of waveforms and add noise to them.

I am trying to add noise to a waveform generated using the get_td_waveform() function thusly.

```
hp, hc = get_td_waveform(approximant="SEOBNRv4_opt",
                         mass1=10,
                         mass2=10,
                         #distance = 1000,
                         delta_t=1.0/4096,
                         f_lower=30)
flow = 30.0
delta_f = 1.0 / 16
flen = int(2048 / delta_f) + 1
psd = pycbc.psd.aLIGOZeroDetHighPower(flen, delta_f, flow)
delta_t = 1.0 / 4096
seconds = float(len(hp)) / 4096
print('Seconds: '+str(seconds))
tsamples = int(seconds / delta_t)
ts = pycbc.noise.noise_from_psd(tsamples, delta_t, psd, seed=127)
combined = hp+ ts
```

Even though the waveform and noise are of equal length, I get an error as the sample_times of the waveform timeseries and noise timeseries don't match. 

Traceback (most recent call last):
  File "add-noise-to-waveform.py", line 49, in <module>
    combined = hp+ts
  File "</home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/decorator.pyc:decorator-gen-29>", line 2, in __add__
  File "/home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/pycbc/types/array.py", line 233, in _returntype
    ary = fn(self,*args) # pylint:disable=not-callable
  File "</home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/decorator.pyc:decorator-gen-28>", line 2, in __add__
  File "/home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/pycbc/types/array.py", line 67, in _convert
    return fn(self, *args)
  File "</home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/decorator.pyc:decorator-gen-27>", line 2, in __add__
  File "/home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/pycbc/types/array.py", line 248, in _checkother
    self._typecheck(other)
  File "/home/.../anaconda3/envs/ligo-py27/lib/python2.7/site-packages/pycbc/types/timeseries.py", line 95, in _typecheck
    raise ValueError('different epoch')
**ValueError: different epoch**

I tried coalign_waveforms() from waveform.utils but that doesn't acheive my goal of simply shifting the start of one of the two time series sample_times to match the other.

Could someone please point me to a correct way of doing this?

Should I rather be using the command line hardware injection way for generating my population of noisy waveforms?

**Comment by rutujagurav** [comment]
Found the appropriate solution for generating synthetic GW data through PyCBC inference module.
