### ISSUE TITLE
Conda installed version pycbc_submit_dax unable to start datafind connection

### ISSUE THREAD

**Issue by paulhopkins** [gwastro/pycbc#2916]
This error was found during running of pycbc_submit_dax, but can be reduced to the following:

```
python -c "from pycbc.frame import datafind_connection; server=datafind_connection()"
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/paul.hopkins/.conda/envs/pycbc_only/lib/python3.7/site-packages/pycbc/frame/frame.py", line 289, in datafind_connection
    host=server, port=port, cert_file=cert_file, key_file=key_file)
  File "/home/paul.hopkins/.conda/envs/pycbc_only/lib/python3.7/site-packages/glue/datafind.py", line 414, in __init__
    http_client.HTTPSConnection.__init__(self, host, **kwargs)
  File "/home/paul.hopkins/.conda/envs/pycbc_only/lib/python3.7/http/client.py", line 1358, in __init__
    blocksize=blocksize)
TypeError: __init__() takes from 1 to 2 positional arguments but 5 were given
```

Also this shows lots of errors from basename, which I did not see before.

**Comment by spxiwh** [comment]
@paulhopkins Do you have a reproducible command that produces this?

Also, while testing python3 is really useful for us, my suspicion is that you are trying to check if ARCCA can run production PyCBC jobs, which currently *must* happen on python2 (and from an environment that does not get updated, so that users in 2 years time can see what code versions were used directly).

So I'd definitely suggest dropping back to python2 for this testing. If CVMFS doesn't work for ARCCA, we should also consider how to create source-able environments for the current PyCBC releases (it is likely that GRB and all-sky will use different releases at any one time).

**Comment by paulhopkins** [comment]
@spxiwh This is definitely a Python3 problem. Using Conda it is possible to install PyCBC with Python3, so you can either use this environment:

```
source /cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/bin/activate ligo-py36
```

or a self installed Conda environments: `conda install -n pycbc_only pycbc`. Although PyCBC is officially Python2 only, PyCBC still provides a lot of useful functionality to other users, so I wouldn't like to see it removed completely. I am just reporting errors until you have finished making it compatible with Python3.

Regarding ARCCA: CVMFS is working but it is not possible to use the supplied virtualenv straight out of the box on bare node. As you say, using the Singularity environment can get around this. On the other-hand Conda is able to provide a complete environment, and is already being used at ARCCA to supply PyCBC with a complete lscsoft Python2.7 environment. I am merely testing what is possible already.

**Comment by spxiwh** [comment]
@paulhopkins Okay great. I just want to distinguish between things that need to be fixed to be able to run production offline runs on ARCCA vs. things that can be fixed some months down the line. I did manage to use `pycbc_submit_dax` fine when I was testing a workflow in python3 some months back. Either something's gone backwards or there's some difference between ARCCA and hypatia in that regard .... Anyway that's some future Ian's problem!

**Comment by paulhopkins** [comment]
To help future Ian with debugging here is the full stack trace and version information:

```
$ conda list pycbc
# packages in environment at /cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36:
#
# Name                    Version                   Build  Channel
pycbc                     1.14.1           py36h516909a_0    conda-forge
```

```
2019-09-10 08:45:13,892:INFO : Setting up connection to datafind server.
Traceback (most recent call last):
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/bin/pycbc_make_coinc_search_workflow", line 131, in <module>
    seg_file=science_seg_file)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/workflow/datafind.py", line 144, in setup_datafind_workflow
    outputDir, tags=tags)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/workflow/datafind.py", line 562, in setup_datafind_runtime_frames_single_call_perifo
    outputDir, tags=tags)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/workflow/datafind.py", line 486, in setup_datafind_runtime_cache_single_call_perifo
    connection = setup_datafind_server_connection(cp, tags=tags)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/workflow/datafind.py", line 832, in setup_datafind_server_connection
    return datafind_connection(datafind_server)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/frame/frame.py", line 289, in datafind_connection
    host=server, port=port, cert_file=cert_file, key_file=key_file)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/glue/datafind.py", line 414, in __init__
    http_client.HTTPSConnection.__init__(self, host, **kwargs)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/http/client.py", line 1367, in __init__
    source_address)
TypeError: __init__() takes from 1 to 2 positional arguments but 5 were given
```

**Comment by spxiwh** [comment]
Okay thanks, this is very helpful .... This actually looks like a bug in `glue.datafind`.
