### ISSUE TITLE
pycbc_coinc_bank2hdf installed with Conda Pytthon2.7 unable to read hdf5 Bank file

### ISSUE THREAD

**Issue by paulhopkins** [gwastro/pycbc#2938]
Using PyCBC installed with Conda and Python2.7 then `pycbc_coinc_bank2hdf` is unable to read a standard Bank file:

```
 pycbc_coinc_bank2hdf   --bank-file   O3_H1L1_OPT_FLOW_HYBRID_BANK.hdf   --output-file   /tmp/H1L1-BANK2HDF-1240333914-677212-.hdf
Traceback (most recent call last):
  File "/home/paul.hopkins/.conda/envs/pycbc_only_py27/bin/pycbc_coinc_bank2hdf", line 105, in <module>
    parameters=columns)
  File "/home/paul.hopkins/.conda/envs/pycbc_only_py27/lib/python2.7/site-packages/pycbc/waveform/bank.py", line 287, in __init__
    names=parameters).fieldnames)
  File "/home/paul.hopkins/.conda/envs/pycbc_only_py27/lib/python2.7/site-packages/pycbc/io/record.py", line 1612, in __new__
    name=name, **kwargs)
  File "/home/paul.hopkins/.conda/envs/pycbc_only_py27/lib/python2.7/site-packages/pycbc/io/record.py", line 760, in __new__
    obj = super(FieldArray, cls).__new__(cls, shape, **kwargs).view(
  File "/home/paul.hopkins/.conda/envs/pycbc_only_py27/lib/python2.7/site-packages/numpy/core/records.py", line 420, in __new__
    descr = sb.dtype(dtype)
TypeError: data type not understood
```

This error occurs with the LSCSoft Python2.7 Conda distribution and a minimal self installed example. Here are the versions of the most relevant libraries:

```
$ conda list "pycbc|numpy|h5py|hdf5|python$" -n pycbc_only_py27
# packages in environment at /home/paul.hopkins/.conda/envs/pycbc_only_py27:
#
# Name                    Version                   Build  Channel
h5py                      2.9.0           nompi_py27h513d04c_1104    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
numpy                     1.14.6          py27he5ce36f_1201    conda-forge
pycbc                     1.14.1           py27h516909a_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
```

The hdf5 file is not corrupted and the command runs successfully when using a Python 3.7 based Conda environment:

```
conda list "pycbc|numpy|h5py|hdf5|python$" -n pycbc_only
# packages in environment at /home/paul.hopkins/.conda/envs/pycbc_only:
#
# Name                    Version                   Build  Channel
h5py                      2.9.0           nompi_py37h513d04c_1104    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
numpy                     1.17.1           py37h95a1406_0    conda-forge
pycbc                     1.14.1           py37h516909a_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
```

**Comment by spxiwh** [comment]
This looks like you've hit https://github.com/gwastro/pycbc/issues/2937. I don't think anyone has yet debugged why this is an incompatibility.

**Comment by spxiwh** [comment]
(It's interesting that this doesn't seem a problem on python3!)

**Comment by josh-willis** [comment]
@spxiwh It is *not* obvious that this is the same as #2937, because Paul is already using `h5py == 2.9.0` when he sees this issue.

**Comment by spxiwh** [comment]
@josh-willis Yes, you're right, I missed that these are similar, but subtly different, errors. Would need some time to debug this!
