### ISSUE TITLE
python3 "KeyError: b'posterior_file'" from pycbc.inference.io.loadfile()

### ISSUE THREAD

**Issue by dbkeitel** [gwastro/pycbc#2944]
I have a pycbc posterior file created under 1.13.8. Using 1.14.1 with python2, it still loads fine. However, with python3:
```
from pycbc.inference.io import loadfile
fp = loadfile('test.hdf','r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/inference/io/__init__.py", line 105, in loadfile
    fileclass = get_file_type(path)
  File "/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/pycbc/inference/io/__init__.py", line 70, in get_file_type
    return filetypes[filetype]
KeyError: b'posterior_file'
```

Looks like one of those pesky byte string conversion issues to me: it seems to want to use a read-from-file byte string as a key to a dict which expects regular strings.

**Comment by dbkeitel** [comment]
Generalised the title of this issue, as after trying to fix the first KeyError, at least two more byte-string-related errors crop up later in loadfile() and read_samples().

**Comment by dbkeitel** [comment]
@spxiwh I'm absolutely with you on the hating! But thanks for the details, and I now also found a "support for python 3 in almost all core modules (inference and tmpltbank not included yet)" warning in the [1.14.0 notes](https://zenodo.org/record/3247679) which unfortunately wasn't repeated explicitly for 1.14.1... ;)
