### ISSUE TITLE
PyCBC Live error on Python 3

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2991]
```
2019-11-02 12:29:06,016 node742 Uploaded PSDs for event G184451
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/bin/pycbc_live", line 765, in <module>
    data_reader, bank)
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/bin/pycbc_live", line 242, in check_coincs
    coinc_results['foreground/{}/template_id'.format(ifos[0])]
TypeError: 'dict_keys' object does not support indexing
```

**Comment by spxiwh** [comment]
```
  File "/home/pycbc.live/testing/O2_replay/pycbc_live_O2_replay_env_py3/bin/pycbc_live", line 242, in check_coincs
    coinc_results['foreground/{}/template_id'.format(ifos[0])]
TypeError: 'dict_keys' object does not support indexing
```

Looks like another of the python3-dicts-are-confusing errors. When assigning `ifos` make this `ifos = list(WHATEVER.keys())`
