### ISSUE TITLE
PyCBC Live broken on master

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#3074]
I am testing PyCBC Live from current master (a4ad429bf52dc7d8bdb63c23584bb20daa7c7582) *without* the `--divide-chunk` option (i.e. using its default). I get this, seemingly coming from #2720:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "…/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "…/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "…/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "…/bin/pycbc_live", line 729, in <module>
    results[ifo] = mf.process_data(data_reader[ifo])
  File "…/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1591, in process_data
    return self.process_all()
  File "…/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1598, in process_all
    result, veto = self._process_batch()
  File "…/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1667, in _process_batch
    segs = [slice(s, e) for s, e in segs]
  File "…/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1667, in <listcomp>
    segs = [slice(s, e) for s, e in segs]
TypeError: 'numpy.float64' object is not iterable
```

**Comment by ahnitz** [comment]
@titodalcanton I had tested this PR a while back, but perhaps there's an issue now. I'll take a quick look, but if it's nothing obvious, let's revert to this back to working on master.

**Comment by titodalcanton** [comment]
I actually think I overlooked these two lines:
```python
segs = numpy.linspace(valid_start, valid_end, num=(1 + self.subdivide))
segs = [slice(s, e) for s, e in segs]
```
How are these going to work? Is `segs` not an array of scalars?

**Comment by titodalcanton** [comment]
Ah, was this the idea?
```python
segs = [slice(s, e) for s, e in zip(segs[0:-1], segs[1:])]
```

**Comment by ahnitz** [comment]
@titodalcanton I'm voting to revert at the moment. I went back to check on my testing directory and could find the folder for this, so it's possible (likely) I completely misremembered given how long ago it was. Consider this untested.

**Comment by titodalcanton** [comment]
Unfortunately it looks like my one-line fix above is not sufficient as it later complains that the slice indexes must be integers. Ok, let's revert for now.

**Comment by ahnitz** [comment]
@titodalcanton I'll re-issue a PR once I can do a test with / without the option.

**Comment by titodalcanton** [comment]
Ok, I am closing this issue for now.
