### ISSUE TITLE
`InjectionSet.write()` problem with approximant field on Python 3

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#3427]
Posting a reduced example to demonstrate the issue described in #3420 and possibly #3395.

I created an HDF injection set as follows:
```bash
pycbc_create_injections \
    --config-files injection_definition.ini \
    --variable-params-section variable_params \
    --static-params-section static_params \
    --dist-section prior \
    --ninjections 5 \
    --output-file injections.hdf \
    --force \
    --verbose
```
with `injection_definition.ini` being:
```
[variable_params]
tc =
mass1 =
mass2 =
ra =
dec =
inclination =
coa_phase =
polarization =
distance =

[static_params]
approximant = IMRPhenomD
f_lower = 12

[prior-tc]
name = uniform
min-tc = 1276524000
max-tc = 1276525000

[prior-mass1]
name = uniform
min-mass1 = 3
max-mass1 = 30

[prior-mass2]
name = uniform
min-mass2 = 3
max-mass2 = 30

[prior-ra+dec]
name = uniform_sky

[prior-inclination]
name = sin_angle

[prior-coa_phase]
name = uniform_angle

[prior-polarization]
name = uniform_angle

[prior-distance]
name = uniform_radius
min-distance = 20
max-distance = 500

[constraint-1]
name = custom
constraint_arg = q_from_mass1_mass2(mass1, mass2) <= 8
```
I then expected something like this to work:
```python
from pycbc.inject import InjectionSet

injs = InjectionSet('injections.hdf')
InjectionSet.write('test.hdf', injs.table)
```
However, I get this:
```
Traceback (most recent call last):
  File "test_injection_io.py", line 4, in <module>
    InjectionSet.write('test.hdf', injs.table)
  File "/Users/tito/anaconda3/lib/python3.7/site-packages/pycbc/inject/inject.py", line 849, in write
    **metadata)
  File "/Users/tito/anaconda3/lib/python3.7/site-packages/pycbc/inject/inject.py", line 437, in write
    fp[field] = samples[field]
  File "/Users/tito/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 387, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/Users/tito/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Users/tito/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1717, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U10')
```
All of the above is running from the same env, using Python 3.7.7 and the current master of PyCBC, 9e97329833f3f2c42d3db601f6956d921ffc623c. The same error happens with slightly different versions of stuff on a different machine. The above code appears to work fine with a Python 2 environment.

**Comment by cdcapano** [comment]
Fixed by #3471
