### ISSUE TITLE
Error : time data with pycbc_geom_aligned_bank

### ISSUE THREAD

**Issue by ChristopherAllene** [gwastro/pycbc#3932]
I try to create a new template bank with pycbc_geom_aligned_bank which is raising an error :

```
/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/bin/pycbc_geom_aligned_bank --pn-order threePointFivePN --f0 10 --f-low 10 --f-upper 80 --delta-f 0.01 --min-match 0.97 --min-mass1 1.0 --min-mass2 1.0 --max-mass1 2.0 --max-mass2 2.0 --min-total-mass 2.0 --max-total-mas 4.0 --max-eta 0.25 --min-eta 0.0 --max-ns-spin-mag 0.05 --psd-model aLIGOZeroDetHighPower --verbose --workflow-name VTBank --intermediate-data-file /home/christopher.allene/halfSNR/80Hz/Template/VTBank/IntermediateBNS40Hz.hdf --metadata-file /home/christopher.allene/halfSNR/80Hz/Template/VTBank/MetaBNS40Hz.xml --output-file /home/christopher.allene/halfSNR/80Hz/Template/VTBank/TemplateBankBNS40Hz.xml --submit-now
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/bin/pycbc_geom_aligned_bank", line 237, in <module>
    ligolw_process.register_to_xmldoc(outdoc, __program__, vars(opts), comment="",
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/lib/python3.9/site-packages/ligo/lw/utils/process.py", line 109, in register_to_xmldoc
    process = proctable.RowType.initialized(program = program, process_id = proctable.get_next_id(), **kwargs)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/lib/python3.9/site-packages/ligo/lw/lsctables.py", line 562, in initialized
    cvs_entry_time = lal.UTCToGPS(time.strptime(cvs_entry_time, "%Y-%m-%d %H:%M:%S +0000")) if cvs_entry_time is not None else None,
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-testing/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S +0000'
```

**Comment by titodalcanton** [comment]
@ChristopherAllene thanks for reporting this. I do not have a lot of time for this at the moment, but we may have to fix `pycbc_geom_aligned_bank` (and related scripts) to work around a recent change in the python-ligo-lw module. We probably want to use [this function](https://github.com/gwastro/pycbc/blob/master/pycbc/io/ligolw.py#L128) instead of calling `register_to_xmldoc()` directly.

**Comment by ChristopherAllene** [comment]
I'm not sure it come from ligo-lw. I cloned the igwn-py39-testing environment with ligo-lw 1.7.0 and it failed (same error).
It might come from the pycbc version. On farmn pycbc is ver 1.8.0 against ver 2.0.1 on CIT server and the farmn is working.

**Comment by titodalcanton** [comment]
This was noticed by two other people, so it is time to get this fixed. I am working on a PR.
