### ISSUE TITLE
AttributeError caused by astropy==5.1

### ISSUE THREAD

**Issue by hoyc1** [gwastro/pycbc#4035]
I get the following error when importing the `psd` module from pycbc:

```python
>>> from pycbc import psd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../pycbc/psd/__init__.py", line 22, in <module>
    from pycbc.psd.variation import *
  File "../pycbc/psd/variation.py", line 10, in <module>
    from pycbc.filter import resample_to_delta_t
  File "../pycbc/filter/__init__.py", line 1, in <module>
    from .matchedfilter import *
  File "../pycbc/filter/matchedfilter.py", line 35, in <module>
    from pycbc import events
  File "../pycbc/events/__init__.py", line 5, in <module>
    from .eventmgr import *
  File "../pycbc/events/eventmgr.py", line 37, in <module>
    from . import coinc, ranking
  File "../pycbc/events/coinc.py", line 28, in <module>
    import numpy, logging, pycbc.pnutils, pycbc.conversions, copy, lal
  File "../pycbc/pnutils.py", line 33, in <module>
    from pycbc import conversions
  File "../pycbc/conversions.py", line 37, in <module>
    import pycbc.cosmology
  File "../pycbc/cosmology.py", line 297, in <module>
    for _c in astropy.cosmology.parameters.available}
  File "../astropy/cosmology/__init__.py", line 38, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}.")
AttributeError: module 'astropy.cosmology' has no attribute 'parameters'.
```

I do not get this error when I have `astropy==5.0.4` installed. I think this error arises because in `astropy==5.1` the list of available cosmologies is stored as `astropy.cosmology.realizations.available` compared to `astropy.cosmology.parameters.available` for `astropy < 5.1`.

**Comment by spxiwh** [comment]
@hoyc1 This sounds like the thing Duncan/Alex fixed in https://github.com/gwastro/pycbc/pull/4022, do you have the latest PyCBC installed (if using earlier versions, probably earlier astropy is needed)

**Comment by hoyc1** [comment]
@spxiwh I am using the latest PyCBC version (pycbc==2.0.2). It looks like #4022 will fix the problem but this was merged into master on 7th May and the latest PyCBC version was released on 2nd March. Is it possible to make a new release which includes this MR?

**Comment by ahnitz** [comment]
@hoyc1 Yes, we should do this. Apologies for not having the release out ahead of time.

**Comment by hoyc1** [comment]
No problem. Thanks!

**Comment by ahnitz** [comment]
@hoyc1 The new release is on PyPI, can you confirm this resolves your issue?
