### ISSUE TITLE
SNR optimization failing in PyCBC Live

### ISSUE THREAD

**Issue by maxtrevor** [gwastro/pycbc#4081]
I am currently trying to run PyCBC Live on some frames on CIT that I have copied over from the MDC. 
When I launch PyCBC Live using the script `/home/max.trevor/CBC/preO4/pycbc_idq/mdc_test/run_saved_frames.sh`  it starts successfully and runs until the first time it finds a coincident event. Then it hits the following error:

```
2022-07-11 10:00:07,894 node1390 0 Coincs 0: H1-L1: 131626 in cbuffer
2022-07-11 10:00:07,895 node1390 0 Found H1-L1 coinc with ifar 0.0024896405191148154
2022-07-11 10:00:07,895 node1390 0 computing followup data for coinc
2022-07-11 10:00:07,896 node1390 0 Generating IMRPhenomD, 16.0s, 168, starting from 20.0 Hz
2022-07-11 10:00:07,995 node1390 0 Coincident candidate! Saving as /local/max.trevor/idq_mdc_test/triggers/coinc-1262302864.3544922-dlxdjv.xml.gz
2022-07-11 10:00:08,044 node1390 0 Source probabilities file saved as /local/max.trevor/idq_mdc_test/triggers/coinc-1262302864.3544922-dlxdjv_probs.json
Traceback (most recent call last):
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/bin/pycbc_live", line 916, in <module>
    evnt.check_coincs(list(results.keys()), best_coinc,
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/bin/pycbc_live", line 384, in check_coincs
    self.setup_optimize_snr(coinc_results, coinc_ifos, bank,
  File "/home/max.trevor/.conda/envs/pycbc-live-mpich/bin/pycbc_live", line 228, in setup_optimize_snr
    tlen = bank.round_up((buff_size + min_buffer) \
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

I have never seen this error before. I am running in my own python environment which I have been using to develop a new statistic for pycbc, but I have confirmed that I can reproduce this error running a completely unmodified installation of PyCBC.

**Comment by titodalcanton** [comment]
@GarethCabournDavies could you have a look? This feels related to #4075.

**Comment by ahnitz** [comment]
@maxtrevor @titodalcanton 

My first though when looking at where the error occurs is that "pycbc.waveform.get_waveform_filter_length_in_time(apr, **p)" must be returning None. This is possible if it thinks it has not method to calculate the length for the given approximant. Also, the other operand in the addition that fails must be a number due to not failing on a previous line where we add a fudge factor to it. 

So this begs the question of why this function is returning none.  When it fails, what does the function return and what was its input? I would add a print statement to capture this if it is reproduceable. I think we can backtrack from there with this information. 

To elminate possibilities, are you confirming that you can run without issue before #4075? The most important thing is to verify that it is a software change and not an issue in configuration (say with the a error in the bank file which has some templates which we don't have a length estimator for).

**Comment by titodalcanton** [comment]
Well, running the test suite using @maxtrevor's Python env works, and it works even if I change the approximant to IMRPhenomD. I am going to look specifically into @maxtrevor's configuration next.

**Comment by titodalcanton** [comment]
```
[…]
2022-07-13 06:58:30,028 ldas-pcdev6 0 Generating IMRPhenomD, 16.0s, 168, starting from 20.0 Hz
2022-07-13 06:58:30,265 ldas-pcdev6 0 Coincident candidate! Saving as triggers/coinc-1262302864.3544922-bjaqlg.xml.gz
2022-07-13 06:58:30,337 ldas-pcdev6 0 Source probabilities file saved as triggers/coinc-1262302864.3544922-bjaqlg_probs.json
2022-07-13 06:58:30,337 ldas-pcdev6 0 About to call get_waveform_filter_length_in_time(b'IMRPhenomD', OrderedDict([('mass1',
 16.307804737407608), ('mass2', 13.635922961130845), ('spin1x', 0.0), ('spin1y', 0.0), ('spin1z', 0.12946161662393807), ('sp
in2x', 0.0), ('spin2y', 0.0), ('spin2z', 0.18456344749112877), ('eccentricity', 0.0), ('lambda1', None), ('lambda2', None), 
('dquad_mon1', None), ('dquad_mon2', None), ('lambda_octu1', None), ('lambda_octu2', None), ('quadfmode1', None), ('quadfmod
e2', None), ('octufmode1', None), ('octufmode2', None), ('dchi0', 0.0), ('dchi1', 0.0), ('dchi2', 0.0), ('dchi3', 0.0), ('dc
hi4', 0.0), ('dchi5', 0.0), ('dchi5l', 0.0), ('dchi6', 0.0), ('dchi6l', 0.0), ('dchi7', 0.0), ('dalpha1', 0.0), ('dalpha2', 
0.0), ('dalpha3', 0.0), ('dalpha4', 0.0), ('dalpha5', 0.0), ('dbeta1', 0.0), ('dbeta2', 0.0), ('dbeta3', 0.0), ('distance', 
1.0), ('coa_phase', 0.0), ('inclination', 0.0), ('long_asc_nodes', 0.0), ('mean_per_ano', 0.0), ('delta_f', None), ('f_lower
', 20.0), ('f_ref', 0), ('phase_order', -1), ('spin_order', -1), ('tidal_order', -1), ('amplitude_order', -1), ('eccentricit
y_order', -1), ('frame_axis', 0), ('modes_choice', 0), ('side_bands', 0), ('mode_array', None), ('f_final', 0), ('f_final_fu
nc', ''), ('delta_t', None), ('numrel_data', ''), ('template_hash', -6895975226166559654), ('template_duration', 3.3778207)]
))
2022-07-13 06:58:30,337 ldas-pcdev6 0 buff_size = None
Traceback (most recent call last):
[…]
```
Hmm, there is a suspicious `b'IMRPhenomD'` in there. I think `get_waveform_filter_length_in_time()` is being confused because the approximant is not a string.

**Comment by titodalcanton** [comment]
Yes, that is the issue. If I pass `'IMRPhenomD'` instead of `b'IMRPhenomD'` to `get_waveform_filter_length_in_time()`, the returned time is 3.377820789299677, which matches the `template_duration` field already present in the template parameters.

We do not normally hit this problem because the banks we use do not carry the approximant specification in them. I thought the bank reading code handled this bytes-vs-string thing transparently?

**Comment by ahnitz** [comment]
@titodalcanton @GarethCabournDavies I think the change needed is here https://github.com/gwastro/pycbc/pull/4075/files#r922239941
