### ISSUE TITLE
PyCBC Live exception in coinc code

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4122]
This happened yesterday to the analysis of MDC O3 replay data, using PyCBC 0.0a8429 / git hash 41beb31b31e8bd3c867b914af048c7e412e23615.
```
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/pool.py", line 41, in _lockstep_fcn
    return fcn(args)
  File "/home/pycbc.live/.conda/envs/conda-test/bin/pycbc_live", line 903, in get_coinc
    r = c.add_singles(results)
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1157, in add_singles
    _, coinc_results = self._find_coincs(results, ifos=valid_ifos)
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1093, in _find_coincs
    trig_id = trigger_ids[ifo][idx]
IndexError: list index out of range
```

**Comment by titodalcanton** [comment]
The analysis was actually in a pretty bad state, as a few filtering processes were struggling to keep up with the data. So the error may be a bug triggered by that.

**Comment by tdent** [comment]
Is this still an issue?

**Comment by titodalcanton** [comment]
Closing as we have not seen this in a long time, will reopen if seen again.
