### ISSUE TITLE
PyCBC Live IndexError exception in coinc code

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4127]
This happened earlier today to the MDC O3 replay analysis.
```
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/pool.py", line 41, in _lockstep_fcn
    return fcn(args)
  File "/home/pycbc.live/.conda/envs/conda-test/bin/pycbc_live", line 903, in get_coinc
    r = c.add_singles(results)
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1229, in add_singles
    self._add_singles_to_buffer(results, ifos=valid_ifos)
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/events/coinc.py", line 999, in _add_singles_to_buffer
    self.singles[ifo].add(trigs['template_id'], data)
  File "/home/pycbc.live/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/events/coinc.py", line 587, in add
    self.buffer[i][curr_pos] = v
IndexError: index 0 is out of bounds for axis 0 with size 0
```
I was running PyCBC 0.0a8435, modified for a smaller rank-0 memory footprint as indicated by @spxiwh, specifically with this change:
```diff
diff --git a/pycbc/events/coinc.py b/pycbc/events/coinc.py
index 26fd8ff6..780640ee 100644
--- a/pycbc/events/coinc.py
+++ b/pycbc/events/coinc.py
@@ -536,8 +536,8 @@ class MultiRingBuffer(object):
         self.valid_ends = []
         self.valid_starts = []
         for _ in range(num_rings):
-            self.buffer.append(numpy.zeros(128, dtype=dtype))
-            self.buffer_expire.append(numpy.zeros(128, dtype=int))
+            self.buffer.append(numpy.zeros(32, dtype=dtype))
+            self.buffer_expire.append(numpy.zeros(32, dtype=int))
             self.valid_ends.append(0)
             self.valid_starts.append(0)
         self.time = 0
```
@spxiwh is the error trivially related to my change, or something that needs more investigation?

**Comment by spxiwh** [comment]
@titodalcanton I tried to envisage how this might happen, and I think there is an edge-case bug here, that having this value smaller might have exposed. In particular we resize the array here:

https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L578

This says "if I am already using all entries in the array, make it bigger". It does this by doubling the size, but if the size is 0 then 2 * 0 is still 0. So I guess I would change:

```
                self.buffer[i] = numpy.resize(
                    self.buffer[i],
                    len(self.buffer[i]) * 2
                )
```

to

```
                self.buffer[i] = numpy.resize(
                    self.buffer[i],
                    min(len(self.buffer[i]) * 2, 32)
                )
```

(and same for the expiry buffer) ... Except then the 32 should become a variable in the class and not hardcoded ...

**Comment by titodalcanton** [comment]
Just noting that this also happened with the main MDC analysis, which is running an unmodified master branch.

**Comment by spxiwh** [comment]
@titodalcanton Do you have the full error stack for the unmodified branch, I don't understand how this might happen in the same place there, but there are other places that might look similar where it is perhaps possible(?)

**Comment by spxiwh** [comment]
Also have you tried the suggested patch for the new code?

**Comment by spxiwh** [comment]
Closing for now. Reopen with another exception if it happens again.
