### ISSUE TITLE
Broken things in the faithsim code

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4145]
@MPillas and I are trying out the faithsim code in preparation for O4. Here is a list of broken things to have a better idea of what needs work to get the code running (in addition to #385).
* [ ] Error in the `.ini`. file described in the documentation, `psd` should be `psd-model`.

**Comment by MPillas** [comment]
When we try running the code with Python3:

`(template_bank_venv) (igwn-py38) [marion.pillas@ldas-pcdev3 ~/projects/template_bank/test_python38]$ pycbc_make_faithsim --conf configuration_pycbc_faithsim.ini 
/home/marion.pillas/template_bank_venv/bin/pycbc_make_faithsim:89: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Warning: accounting-group not specified, LDG clusters may'
2022-10-03 08:02:08,268 Warning: accounting-group not specified, LDG clusters may reject this workflow!
2022-10-03 08:02:08,268 Making workspace directories
2022-10-03 08:02:08,270 Copying scripts
2022-10-03 08:02:08,272 Creating injection file
2022-10-03 08:02:08,470 Splitting template bank
2022-10-03 08:02:15,730 Creating DAG
Traceback (most recent call last):
  File "/home/marion.pillas/template_bank_venv/bin/pycbc_make_faithsim", line 119, in <module>
    dag.set_dax_file("faithsim")
AttributeError: 'CondorDAG' object has no attribute 'set_dax_file'`

**Comment by spxiwh** [comment]
`set_dax_file` was removed from pipeline.py, it just needs removing.

.... Yeah, this code isn't aging well, needs moving over to a pegasus workflow, and needs a proper unit test. The `can't multiply sequence by non-int of type 'float'` looks like a "need to do integer division in python3" problem.

**Comment by titodalcanton** [comment]
Partially fixed by #4154.

**Comment by MPillas** [comment]
Problem in `pycbc_faithsim_collect_results` (`part of pycbc_make_faithsim`)

`Traceback (most recent call last):
  File "scripts/pycbc_faithsim_collect_results", line 50, in <module>
    pdata[field] = bt.get_column(field)
AttributeError: 'SimInspiralTable' object has no attribute 'get_column'`

But in the documentation I can clearly see the attribute `get_column` in the `glue.ligolw.lsctables.SimInspiralTable` class. The problem comes from the `mass1` column otherwise the code working.

**Comment by titodalcanton** [comment]
@MPillas `glue.ligolw.lsctables.SimInspiralTable` is part of the old `glue` module, which we no longer use. The thing to look at now is `ligo.lw.lsctables.SimInspiralTable` whose source code is [here](https://git.ligo.org/kipp.cannon/python-ligo-lw/-/blob/master/ligo/lw/lsctables.py#L1265), and indeed I think the `get_column()` method has been dropped. Something like should work though:
```
snr_list = si_table.getColumnByName('snr').asarray()
```
