### ISSUE TITLE
Error with inference example with Python ≥3.10

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4244]
Trying to build the documentation offline, I found that running `/examples/inference/single/run_instant.sh` sometimes produces the following error:
```
2023-01-19 18:37:18,501 Using seed 0
2023-01-19 18:37:18,501 Running with CPU support: 1 threads
2023-01-19 18:37:18,586 Reading configuration file
2023-01-19 18:37:18,587 Setting up model
2023-01-19 18:37:18,588 Setting up priors for each parameter
2023-01-19 18:37:18,589 No sampling_params section read from config file
2023-01-19 18:37:18,591 Determining analysis times to use
2023-01-19 18:37:18,591 Padding H1 analysis start and end times by 8 (= psd-inverse-length/2) seconds to account for PSD wrap around effects.
2023-01-19 18:37:18,591 Padding L1 analysis start and end times by 8 (= psd-inverse-length/2) seconds to account for PSD wrap around effects.
2023-01-19 18:37:18,591 Padding V1 analysis start and end times by 8 (= psd-inverse-length/2) seconds to account for PSD wrap around effects.
2023-01-19 18:37:18,591 Reading Frames
2023-01-19 18:37:21,640 Highpass Filtering
2023-01-19 18:37:21,791 Resampling data
2023-01-19 18:37:23,509 Converting to float64
2023-01-19 18:37:23,512 Highpass Filtering
2023-01-19 18:37:23,584 Remove Padding
2023-01-19 18:37:23,585 Reading Frames
2023-01-19 18:37:26,740 Highpass Filtering
2023-01-19 18:37:26,858 Resampling data
2023-01-19 18:37:27,654 Converting to float64
2023-01-19 18:37:27,655 Highpass Filtering
2023-01-19 18:37:27,725 Remove Padding
2023-01-19 18:37:27,726 Reading Frames
2023-01-19 18:37:30,901 Highpass Filtering
2023-01-19 18:37:31,050 Resampling data
2023-01-19 18:37:31,742 Converting to float64
2023-01-19 18:37:31,743 Highpass Filtering
2023-01-19 18:37:31,816 Remove Padding
Traceback (most recent call last):
  File "/home/tito/.conda/envs/pycbc-dev-py39/bin/pycbc_inference", line 129, in <module>
    model = models.read_from_config(cp)
  File "/home/tito/.conda/envs/pycbc-dev-py39/lib/python3.9/site-packages/pycbc/inference/models/__init__.py", line 183, in read_from_config
    return get_model(name).from_config(cp, **kwargs)
  File "/home/tito/.conda/envs/pycbc-dev-py39/lib/python3.9/site-packages/pycbc/inference/models/gaussian_noise.py", line 613, in from_config
    return cls(**args)
  File "/home/tito/.conda/envs/pycbc-dev-py39/lib/python3.9/site-packages/pycbc/inference/models/single_template.py", line 77, in __init__
    variable_params, kwargs = self.setup_distance_marginalization(
TypeError: pycbc.inference.models.tools.DistMarg.setup_distance_marginalization() got multiple values for keyword argument 'marginalize_vector_params'
```
This seems to depend on the Python env, although I have not figured out what exactly it depends on.

@WuShichao @cdcapano any idea?

**Comment by ahnitz** [comment]
@titodalcanton In fact, I'm quite confused here. The method that it complains about does not exist on master.

Can you confirm if this is based form an old version (if so which one) ? Do you see this if you run from master?
