### ISSUE TITLE
TypeError in PyCBC Live's coinc code

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4270]
From the EW analysis today:
```
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/site-packages/pycbc/pool.py", line 41, in _lockstep_fcn
    return fcn(args)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/bin/pycbc_live", line 960, in get_coinc
    r = c.add_singles(results)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1329, in add_singles
    _, coinc_results = self._find_coincs(results, valid_ifos=valid_ifos)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1260, in _find_coincs
    zerolag_results['foreground/ifar'] = self.ifar(zerolag_cstat)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1002, in ifar
    n = self.coincs.num_greater(coinc_stat)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-ew-env/lib/python3.9/site-packages/pycbc/events/coinc.py", line 803, in num_greater
    return coincbuffer_numgreater(self.buffer, self.index, value)
  File "pycbc/events/eventmgr_cython.pyx", line 247, in pycbc.events.eventmgr_cython.coincbuffer_numgreater
TypeError: only size-1 arrays can be converted to Python scalars
```

**Comment by spxiwh** [comment]
I have a hunch (and don't think this is a new bug). SOOOO

The failure happens here:

https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L803

and the error can only happen if either `self.index` or `value` is a numpy array with not exactly one value in it.

`self.index` is an integer, and as far as I can see (I didn't exhaust *all* possibilities) will always be an integer.

`value` is weird. It's coming from this call here:

https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L1260

so what is `zerolag_cstat`? That's defined here:

https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L1259

and is not entirely trivial as both as the index values here are arrays defined here:

https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L1235

Now I think what is supposed to happen is that `cidx` is an array of indexes (potentially many), but `zerolag_idx` should be a boolean array with only one `True` value. So in short, there can only be one zero-lag trigger in any block.

If there's *more than one* zero-lag trigger, this is going to break, in the way you see.

In the *old* code, this would still break, but with an error more like:

```
ValueError: operands could not be broadcast together with shapes (X,) (2,)
```

Am I remembering right about the "only one zero-lag trigger every time" rule?

**Comment by ahnitz** [comment]
@spxiwh Yes, you are thinking right here. It expects at most one zerolag trigger after the clustering step.

**Comment by ahnitz** [comment]
Clearly there is a mistake where 2 can be produced.

**Comment by ahnitz** [comment]
@titodalcanton @spxiwh That's my best guess. This, but I think it can happen this way. Looking in the code, in fact, I think the error I described must occur at some rate.

**Comment by ahnitz** [comment]
@titodalcanton @spxiwh I think this should be reproduceable (or at least one should be able to force the scenario I just discussed). In that case, I think the solution would be to just increase the clustering window (by earth crossing time).

**Comment by ahnitz** [comment]
Also, this is more likely to occur in the EW analysis because presumably you are using a shorter chunk length. The relative rate of this happening would increase more than linearly (something like quadratic or cubic).

**Comment by titodalcanton** [comment]
For the record this happened again today.

**Comment by titodalcanton** [comment]
Well this has not happened in a while, hence I am closing.
