### ISSUE TITLE
Error from SNR optimizer

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4303]
This came from a trigger very close to the boundary of an analysis segment.
```
2023-03-30T08:08:06.360-07:00 Running with CPU support: 1 threads
2023-03-30T08:08:07.796-07:00 Starting optimize SNR
2023-03-30T08:08:07.804-07:00 Following up GID G970459
2023-03-30T08:08:07.807-07:00 Starting optimization
/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/optimize/_differentialevolution.py:382: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  with DifferentialEvolutionSolver(func, bounds, args=args,
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/_lib/_util.py", line 372, in __call__
    return self.f(x, *self.args)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/bin/pycbc_optimize_snr", line 116, in compute_minus_network_snr
    nsnr, _ = compute_network_snr_core(v, *argv)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/bin/pycbc_optimize_snr", line 105, in compute_network_snr_core
    snr_series = snr[onsource_slice] * norm
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/pycbc/types/array.py", line 65, in convert
    return func(self, *args, **kwargs)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/pycbc/types/array.py", line 819, in __getitem__
    return self._getslice(index)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/pycbc/types/timeseries.py", line 131, in _getslice
    raise ValueError(('Negative start index ({})'
ValueError: Negative start index (-1107) not supported
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/optimize/_differentialevolution.py", line 1123, in _calculate_population_energies
    self._mapwrapper(self.func, parameters_pop[0:S])
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/_lib/_util.py", line 442, in __call__
    return self._mapfunc(func, iterable)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Negative start index (-1107) not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/o4-prod-env/bin/pycbc_optimize_snr", line 348, in <module>
    opt_params = optimize_func(bounds, args, extra_args)
  File "/home/pycbc.live/.conda/envs/o4-prod-env/bin/pycbc_optimize_snr", line 133, in optimize_di
    results = differential_evolution(
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/optimize/_differentialevolution.py", line 397, in differential_evolution
    ret = solver.solve()
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/optimize/_differentialevolution.py", line 989, in solve
    self._calculate_population_energies(
  File "/home/pycbc.live/.conda/envs/o4-prod-env/lib/python3.9/site-packages/scipy/optimize/_differentialevolution.py", line 1129, in _calculate_population_energies
    raise RuntimeError(
RuntimeError: The map-like callable must be of the form f(func, iterable), returning a sequence of numbers the same length as 'iterable'
```

**Comment by spxiwh** [comment]
Do we have any way to reproduce this?

**Comment by spxiwh** [comment]
Just going through my to-do list: I'm happy to try and track this down this week, but would be great if the files that reproduce this are available (presumably behind LVK auth).

**Comment by titodalcanton** [comment]
I forget if we ever addressed this one… @maxtrevor?

**Comment by maxtrevor** [comment]
> I forget if we ever addressed this one… @maxtrevor?

I don't think we did but there have been a lot of changes to the snr optimizer that may have inadvertently fixed it? I'm happy with closing this and reopening if this error ever crops up again.

**Comment by GarethCabournDavies** [comment]
Was this the buffer-not-long-enough thing?

**Comment by maxtrevor** [comment]
> Was this the buffer-not-long-enough thing?

No I think its a separate problem

**Comment by titodalcanton** [comment]
I cannot find the G event anymore on gracedb-playground, but I traced the event directory down to
```
/home/pycbc.live/analysis/test/2022_ll_mdc_o3_replay/full_bandwidth/cit/triggers/2023_03_30/candidate_1364224068.076_vcvr/optimize_snr
```

**Comment by GarethCabournDavies** [comment]
(mainly a note for myself) I have reproduced this in: /home/gareth.cabourndavies/test_codes/pycbclive/snr_opt_error

**Comment by spxiwh** [comment]
From Gareth's test: The data stored for the event spans 1364224068.569335938  - 1364224092.569335938. The trigger time is at 1364224068.0761719 ... so hard for it to do any followup here. Not sure why this logic failed and it stored the wrong data, but it certainly is not an issue in the optimizer itself ... Also cannot tell if the underlying bug is already fixed!

**Comment by titodalcanton** [comment]
@spxiwh then this does indeed look like the data race condition which we fixed a while ago in https://github.com/gwastro/pycbc/pull/4342.

**Comment by GarethCabournDavies** [comment]
I think we can close this then?
