### ISSUE TITLE
pycbc_plot_singles_timefreq doesn't work with SEOBNRv5_ROM

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4496]
Using SEOBNRv5_ROM templates results in:

```
        Traceback (most recent call last):
          File "/home/ian.harry/virtualenvs/pycbc_python3_throwawaytest4/bin/pycbc_plot_singles_timefreq", line 159, in <module>
            track_t, track_f = pycbc.pnutils.get_inspiral_tf(
          File "/home/ian.harry/virtualenvs/pycbc_python3_throwawaytest4/lib/python3.9/site-packages/pycbc/pnutils.py", line 595, in get_inspiral_tf
            raise ValueError('Approximant ' + approximant + ' not supported')
        ValueError: Approximant SEOBNRv5_ROM not supported
```

**Comment by titodalcanton** [comment]
Right, pnutils needs a change as well. I can do this unless you are.

**Comment by spxiwh** [comment]
I hadn't started on this, so if you want to do it first, that's fine with me :-)
