### ISSUE TITLE
pycbc_inference fails to set up sampler

### ISSUE THREAD

**Issue by Tobias-Reike** [gwastro/pycbc#4627]
Hello, i am having trouble using pycbc_inference as the tutorial "Running on an analytic distribution" does. I set up a new virtual environment where i installed pycbc with pip. then i ran the pycbc_inference command as instructed with the inputfile from the tutorial:
pycbc_inference --verbose 
                              --config-files normal2d.ini 
                              --output-file normal2d.hdf 
                              --nprocesses 2 
                              --seed 10 
                              --force

I get the error:
2024-02-09T17:17:05.253+01:00 Setting up sampler
Traceback (most recent call last):
  File "path/env/bin/pycbc_inference", line 137, in <module>
    sampler = inference.sampler.load_from_config(
  File "path/env/lib/python3.10/site-packages/pycbc/inference/sampler/__init__.py", line 95, in load_from_config
    return samplers[name].from_config(cp, model, **kwargs)
KeyError: 'emcee'

The command fails to set up a sampler, as it does not have the key 'emcee'. However the file emcee.py is in the sampler directory and i cant find any other reason why this error should occur.

**Comment by ahnitz** [comment]
@Tobias-Reike That is probably because you may not have the specific sampler, emcee installed (or the right version). Can you do 

```
pip install emcee=2.2.1
```

Can let me know if there is still an error?

**Comment by Tobias-Reike** [comment]
@ahnitz It works now, thank you for the quick response. Apparently i had the wrong version of emcee.

**Comment by ahnitz** [comment]
@Tobias-Reike No worries, the error message could be more informative. If you were code inclined, you could perhaps help us make the message more clear that we don't detect the presence of the sampler requested.
