### ISSUE TITLE
pycbc.inference option_utils is broken

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4663]
When running a code which uses
```
from pycbc.inference import option_utils
```
 We see the following error:
```
pycbc_plot_bank_corner --help
Traceback (most recent call last):
  File "/home/gareth.cabourndavies/test_codes/pycbc/standardize_logging/env_standard_logging/bin/pycbc_plot_bank_corner", line 34, in <module>
    from pycbc.inference import option_utils
  File "/home/gareth.cabourndavies/test_codes/pycbc/standardize_logging/env_standard_logging/src/pycbc/pycbc/inference/__init__.py", line 2, in <module>
    from . import (models, sampler, io)
  File "/home/gareth.cabourndavies/test_codes/pycbc/standardize_logging/env_standard_logging/src/pycbc/pycbc/inference/models/__init__.py", line 38, in <module>
    from .relbin import Relative, RelativeTime, RelativeTimeDom
  File "/home/gareth.cabourndavies/test_codes/pycbc/standardize_logging/env_standard_logging/src/pycbc/pycbc/inference/models/relbin.py", line 40, in <module>
    from .relbin_cpu import (likelihood_parts, likelihood_parts_v,
ImportError: cannot import name 'likelihood_parts_det_multi' from 'pycbc.inference.models.relbin_cpu' (/home/gareth.cabourndavies/test_codes/pycbc/standardize_logging/env_standard_logging/src/pycbc/pycbc/inference/models/relbin_cpu.cpython-39-x86_64-linux-gnu.so)
```

I don't know this code well enough to point to any changes in this which should have been imported?

**Comment by ahnitz** [comment]
@GarethCabournDavies I can't reproduce this and the script doesn't exist in master it would seem. Maybe this is something local to your environment or specific to a version of python or external package? 

```
Python 3.11.8 (main, Feb 28 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pycbc.inference import option_utils

In [2]: 
```

**Comment by GarethCabournDavies** [comment]
The script is in master, in `bin/plotting`, but a simple reinstall of pycbc fixed this, so I will close with a "I don't know how this was broken but it isn't anymore"
