### ISSUE TITLE
Allow PyCBC Live to run with only one IFO provided

### ISSUE THREAD

**Issue by maxtrevor** [gwastro/pycbc#4669]
Currently the PyCBC Live search requires at least two ifos that are able to be used for estimating significance (i.e. not set as skymap-only). 
Attempting to run PyCBC Live while providing only a single ifo gives the following error:

```
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/o4-test-env/bin/pycbc_live", line 1182, in <module>
    coinc_pool = BroadcastPool(len(estimators))
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/site-packages/pycbc/pool.py", line 56, in __init__
    super(BroadcastPool, self).__init__(processes, noint, initargs, **kwds)
  File "/home/pycbc.live/.conda/envs/o4-test-env/lib/python3.9/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```
The error seems to happen because PyCBC Live attempts to form an MPI pool with 0 Coincer objects

**Comment by titodalcanton** [comment]
I suppose the desired solution is to behave as if `args.enable_background_estimation` was `False` when only one detector is used for the search.

**Comment by titodalcanton** [comment]
…though I am not sure it makes a lot of sense to use `--enable-background-estimation` and provide a single searching detector? Maybe the best thing to do is just error out and say that is not a valid operation mode.

**Comment by maxtrevor** [comment]
Looking at this now, turning off `--enable-background-estimation` does what I want. I think this option could use a better name though, I would not have guessed thats what I needed to turn off to enable a single detector search. Maybe `--enable-coincident-search` ? and then I would agree that it should just error out if that option is given but only one ifo is given for significance..

**Comment by GarethCabournDavies** [comment]
Should we close this issue, or assign someone to rename the option?
