### ISSUE TITLE
plot_singles_vs_params failing

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4993]
The latest CI searches are failing on plot_singles_vs_params:
```
        Traceback (most recent call last):
          File "/opt/hostedtoolcache/Python/3.10.15/x64/bin/pycbc_plot_singles_vs_params", line 178, in <module>
            hb = ax.hexbin(x, y, C=z, reduce_C_function=np.max, **hexbin_style)
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 453, in wrapper
            return func(*args, **kwargs)
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/__init__.py", line 1521, in inner
            return func(
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5293, in hexbin
            [reduce_C_function(acc) if len(acc) >= mincnt else np.nan
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5293, in <listcomp>
            [reduce_C_function(acc) if len(acc) >= mincnt else np.nan
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/numpy/_core/fromnumeric.py", line 3164, in max
            return _wrapreduction(a, np.maximum, 'max', axis, None, out,
          File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/numpy/_core/fromnumeric.py", line 86, in _wrapreduction
            return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
        ValueError: zero-size array to reduction operation maximum which has no identity
        
```

Opinion: I don't actually think the problem is definitely in plot_singles_vs_params - I have a hunch it is in a code upstream which leads to nothing being in the input file. There are enough catches in plot_singles_vs_params for things being filtered out that I think it is safe

**Comment by spxiwh** [comment]
@GarethCabournDavies Any update on understanding this?

**Comment by GarethCabournDavies** [comment]
I haven't been able to get the CI search running locally to check

I have manually removed triggers from a `hdf_trigger_merge` file, and it ran without failing, so that hunch was wrong

**Comment by titodalcanton** [comment]
Could you download the artifacts from the CI run, and run the plotting script locally on the HDF file you downloaded?

**Comment by GarethCabournDavies** [comment]
> Could you download the artifacts from the CI run, and run the plotting script locally on the HDF file you downloaded?

The files themselves don't get saved - only the logs (which is annoying)

**Comment by GarethCabournDavies** [comment]
The problem is in the version comparison [here](https://github.com/gwastro/pycbc/blob/23388834ff02e17411c9b692e2a670cdcd90c599/bin/plotting/pycbc_plot_singles_vs_params#L151) - as the string comparison doesn't handle semantic versioning, so matplotlib v3.10 is less then v3.8.1

I'll add a bugfix
